fix: streamline file handling in clipfiles script
Refactor the clipfiles script to improve handling
of directory and file arguments. The script now
supports multiple paths, checks for binary files,
and provides clearer error messages for invalid
paths. This update enhances the usability and
robustness of the script when managing file input.

Signed-off-by: Denis Yuji Shimizu <denis.shimizu@collabora.com>

diff --git a/clipfiles b/clipfiles
--- a/clipfiles
+++ b/clipfiles
@@ -3,7 +3,9 @@
 # Usage: ./clipfiles.sh [<path>]
 
 # Default to current directory if no argument is provided
-PATH_ARG="${1:-.}"
+if [ "$#" -eq 0 ]; then
+  set -- "."
+fi
 
 # Variable to accumulate all output
 OUTPUT=""
@@ -15,41 +17,31 @@ is_binary() {
 }
 
 # If the argument is a directory
-if [ -d "$PATH_ARG" ]; then
-  cd "$PATH_ARG" || {
-    echo "Cannot change to directory: $PATH_ARG"
-    exit 1
-  }
-  
-  # Gather data for all non-hidden and non-binary files
-  while IFS= read -r FILE; do
-    if ! is_binary "$FILE"; then
-      OUTPUT+=$'\n'"$FILE"$'\n'
+for ARG in "$@"; do
+  if [ -d "$ARG" ]; then
+    while IFS= read -r FILE; do
+      if ! is_binary "$FILE"; then
+        OUTPUT+=$'\n'"$FILE"$'\n'
+        OUTPUT+='```'$'\n'
+        OUTPUT+="$(cat "$FILE")"$'\n'
+        OUTPUT+='```'$'\n'
+      else
+        echo "Skipping binary file: $FILE"
+      fi
+    done < <(find "$ARG" -mindepth 1 \( -type d -name '.*' -prune \) -o \( -type f ! -iname '*README*' ! -iname '*LICENSE*' -print \))
+  elif [ -f "$ARG" ]; then
+    if ! is_binary "$ARG"; then
+      OUTPUT+=$'\n'"$ARG"$'\n'
       OUTPUT+='```'$'\n'
-      OUTPUT+="$(cat "$FILE")"$'\n'
+      OUTPUT+="$(cat "$ARG")"$'\n'
       OUTPUT+='```'$'\n'
     else
-      echo "Skipping binary file: $FILE"
+      echo "Skipping binary file: $ARG"
     fi
-  done < <(find . -mindepth 1 \( -type d -name '.*' -prune \) -o \( -type f ! -iname '*README*' ! -iname '*LICENSE*' -print \))
-
-# If the argument is a file
-elif [ -f "$PATH_ARG" ]; then
-  if ! is_binary "$PATH_ARG"; then
-    OUTPUT+="$PATH_ARG"$'\n'
-    OUTPUT+='```'$'\n'
-    OUTPUT+="$(cat "$PATH_ARG")"$'\n'
-    OUTPUT+='```'$'\n'
   else
-    echo "Skipping binary file: $PATH_ARG"
-    exit 1
+    echo "Invalid path: $ARG"
   fi
-
-# If the path is invalid
-else
-  echo "Invalid path: $PATH_ARG"
-  exit 1
-fi
+done
 
 # Copy to clipboard if OUTPUT is not empty
 if [[ -n "$OUTPUT" ]]; then
